name: Terraform Workflow

on:
  push:
    paths:
      - 'terraform/dev/spoke_vnet/**'
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        directory: ${{ github.event.commits.*.modified | map(x => x | split('/')[:-1] | join('/')) | unique }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Terraform Format Check
        working-directory: ${{ matrix.directory }}
        run: |
          if [ -f "main.tf" ]; then
            terraform fmt -check -recursive
          else
            echo "No main.tf found in ${{ matrix.directory }}. Skipping."