name: Terraform Workflow

on:
  push:
    paths:
      - 'terraform/virtual_hub/**'
      - 'terraform/dev/**'
      - 'terraform/prod/**'
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        directory: ${{ fromJson('[' + join(',', github.event.commits.*.modified | map(x => x | split("/")[:-1] | join("/")) | unique | map(x => '"' + x + '"')) + ']') }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set Working Directory
        id: set-dir
        run: |
          echo "Working directory: ${{ matrix.directory }}"
          echo "::set-output name=working-directory::${{ matrix.directory }}"

      - name: Pwd
        working-directory: ${{ matrix.directory }}
        run: pwd

      - name: Terraform Format Check
        working-directory: ${{ matrix.directory }}
        run: |
          if [ -f "main.tf" ]; then
            terraform fmt -check -recursive
          else
            echo "No main.tf found in ${{ matrix.directory }}. Skipping."