name: Terraform Workflow

on:
  push:
    paths:
      - 'terraform/dev/spoke_vnet/**'
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Extract modified directories
        id: extract_dirs
        run: |
          dirs=$(jq -r '[.commits[].modified[] | select(test("^terraform/dev/spoke_vnet/")) | split("/")[0:-1] | join("/") | unique] | .[]' < "${GITHUB_EVENT_PATH}")
          echo "directories=${dirs}" >> $GITHUB_ENV

      - name: Terraform Format Check
        if: ${{ fromJson(env.directories) }}
        run: |
          for dir in ${{ fromJson(env.directories) }}; do
            if [ -f "${dir}/main.tf" ]; then
              echo "Running terraform fmt in ${dir}"
              terraform fmt -check -recursive "${dir}"
            else
              echo "No main.tf found in ${dir}. Skipping."
            fi
          done