name: Terraform Workflow

on:
  push:
    paths:
      - 'terraform/dev/**'
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        directory: ${{ fromJson('[' + join(',', github.event.commits.*.modified | map(x => x | split('/')[0:3] | join('/')) | unique | map(x => '"' + x + '"')) + ']') }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set Working Directory
        id: set-dir
        run: |
          echo "Working directory: ${{ matrix.directory }}"
          echo "::set-output name=working-directory::${{ matrix.directory }}"

      - name: Terraform Format Check
        working-directory: ${{ matrix.directory }}
        run: terraform fmt -check -recursive